import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:intl/intl.dart';
import 'package:image_picker/image_picker.dart';
import 'package:longinset/services/archive_service.dart';
import 'package:longinset/features/current_affairs.dart';
import 'package:longinset/features/pdf_generator.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await Supabase.initialize(
    url: 'YOUR_SUPABASE_URL',
    anonKey: 'YOUR_SUPABASE_ANON_KEY',
  );
  runApp(const MyApp());
}

// --- APP THEME CONSTANTS ---
class AppTheme {
  static const Color primary = Colors.indigoAccent;
  static const Color slate = Color(0xFF1E293B); // Slate-800
  static const Color background = Color(0xFF0F172A); // Slate-900
  static const Color surface = Color(0xFF334155); // Slate-700
  static const Color text = Color(0xFFF1F5F9); // Slate-100
}

class PdfService {
  static Future<void> generateAndDownload(String title, String content) async {
    final pdf = pw.Document();
    
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Stack(
            children: [
              // Watermark
              pw.Center(
                child: pw.Transform.rotate(
                  angle: -0.5,
                  child: pw.Opacity(
                    opacity: 0.1,
                    child: pw.Text('Keyan ARTS', style: pw.TextStyle(fontSize: 80, color: PdfColors.grey400, fontWeight: pw.FontWeight.bold)),
                  ),
                ),
              ),
              // Content
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('KEYAN GROUPS ARCHIVAL REPORT', style: pw.TextStyle(fontSize: 10, color: PdfColors.indigo900)),
                  pw.SizedBox(height: 20),
                  pw.Text(title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.black)),
                  pw.Divider(thickness: 2, color: PdfColors.indigoAccent),
                  pw.SizedBox(height: 20),
                  pw.Text(content, style: pw.TextStyle(fontSize: 12, lineSpacing: 1.5)),
                  pw.Spacer(),
                  pw.Divider(),
                  pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Text('Generated by Keyan Groups AI Protocol', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
                          pw.UrlLink(
                            child: pw.Text("Developed by: Karthikeyan S", style: const pw.TextStyle(fontSize: 8, color: PdfColors.blue, decoration: pw.TextDecoration.underline)),
                            destination: "https://karthikeyans2006.github.io/",
                          ),
                          pw.UrlLink(
                            child: pw.Text("GitHub: KarthikeyanS2006", style: const pw.TextStyle(fontSize: 8, color: PdfColors.blue, decoration: pw.TextDecoration.underline)),
                            destination: "https://github.com/KarthikeyanS2006/",
                          ),
                        ],
                      ),
                      pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
                    ],
                  ),
                ],
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Keyan Groups Archival Vault',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.dark,
        primaryColor: AppTheme.primary,
        scaffoldBackgroundColor: AppTheme.background,
        colorScheme: const ColorScheme.dark(
          primary: AppTheme.primary,
          secondary: Colors.tealAccent,
          surface: AppTheme.surface,
          background: AppTheme.background,
        ),
        textTheme: GoogleFonts.outfitTextTheme(ThemeData.dark().textTheme),
        useMaterial3: true,
      ),
      home: const AuthGate(),
    );
  }
}

class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<AuthState>(
      stream: Supabase.instance.client.auth.onAuthStateChange,
      builder: (context, snapshot) {
        final session = snapshot.data?.session ?? Supabase.instance.client.auth.currentSession;
        if (session != null) {
          return const HomePage();
        }
        return const LoginPage();
      },
    );
  }
}

class LoginPage extends StatefulWidget {
  const LoginPage({super.key});
  @override
  State<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  final _email = TextEditingController();
  final _pass = TextEditingController();
  bool _loading = false;
  bool _isLogin = true;

  Future<void> _authAction() async {
    if (_email.text.isEmpty || _pass.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please fill all fields')));
      return;
    }

    setState(() => _loading = true);
    try {
      if (!_isLogin) {
        await Supabase.instance.client.auth.signUp(email: _email.text, password: _pass.text);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Verification email sent! Check your inbox.')),
          );
        }
      } else {
        await Supabase.instance.client.auth.signInWithPassword(email: _email.text, password: _pass.text);
      }
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: ${e.toString()}')));
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.background,
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(32.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.shield_moon_outlined, size: 80, color: AppTheme.primary),
              const SizedBox(height: 24),
              Text(
                'KEYAN GROUPS',
                style: GoogleFonts.outfit(fontSize: 32, fontWeight: FontWeight.bold, letterSpacing: 2, color: AppTheme.text),
              ),
              Text(
                'SECURE ARCHIVAL VAULT',
                style: GoogleFonts.outfit(fontSize: 14, letterSpacing: 4, color: Colors.blueGrey),
              ),
              const SizedBox(height: 48),
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: AppTheme.surface,
                  borderRadius: BorderRadius.circular(16),
                  boxShadow: [
                    BoxShadow(color: Colors.black.withValues(alpha: 0.2), blurRadius: 10, offset: const Offset(0, 4)),
                  ],
                ),
                child: Column(
                  children: [
                    TextField(
                      controller: _email,
                      style: const TextStyle(color: Colors.white),
                      decoration: InputDecoration(
                        labelText: 'Email',
                        labelStyle: const TextStyle(color: Colors.blueGrey),
                        prefixIcon: const Icon(Icons.email_outlined, color: AppTheme.primary),
                        filled: true,
                        fillColor: AppTheme.slate,
                        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
                      ),
                    ),
                    const SizedBox(height: 16),
                    TextField(
                      controller: _pass,
                      obscureText: true,
                      style: const TextStyle(color: Colors.white),
                      decoration: InputDecoration(
                        labelText: 'Password',
                        labelStyle: const TextStyle(color: Colors.blueGrey),
                        prefixIcon: const Icon(Icons.lock_outline, color: AppTheme.primary),
                        filled: true,
                        fillColor: AppTheme.slate,
                        border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide.none),
                      ),
                    ),
                    const SizedBox(height: 24),
                    SizedBox(
                      width: double.infinity,
                      height: 56,
                      child: ElevatedButton(
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppTheme.primary,
                          foregroundColor: Colors.white,
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                          elevation: 0,
                        ),
                        onPressed: _loading ? null : _authAction,
                        child: _loading
                            ? const CircularProgressIndicator(color: Colors.white)
                            : Text(_isLogin ? 'LOGIN' : 'REGISTER', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                      ),
                    ),
                  ],
                ),
              ).animate().fadeIn(delay: 200.ms).slideY(begin: 0.1),
              const SizedBox(height: 24),
              TextButton(
                onPressed: () => setState(() => _isLogin = !_isLogin),
                child: Text(
                  _isLogin ? 'Create Account' : 'Back to Login',
                  style: const TextStyle(color: Colors.blueGrey),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});
  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final _client = Supabase.instance.client;
  String _searchQuery = '';
  final _searchController = TextEditingController();
  final ImagePicker _picker = ImagePicker();

  Stream<List<Map<String, dynamic>>> get _stream {
    return _client.from('incidents').stream(primaryKey: ['id']).order('incident_date', ascending: false);
  }

  Map<String, String>? _currentReport;

  Future<void> _pickAndConvertImages() async {
    try {
      final List<XFile> images = await _picker.pickMultiImage();
      if (images.isNotEmpty) {
        if (mounted) {
           ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Generating PDF Report...')),
          );
        }
        await ImageToPdfService.generatePdfFromImages(images);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  Future<void> _addIncident() async {
    final titleController = TextEditingController();
    final descController = TextEditingController();
    final dateController = TextEditingController(text: DateTime.now().toString().split(' ')[0]);

    await showDialog(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: const Color(0xFF1B1B2F),
        title: Text('New Archival Entry', style: GoogleFonts.outfit(fontWeight: FontWeight.bold)),
        content: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextField(
                controller: titleController,
                decoration: const InputDecoration(labelText: 'Incident Title', hintText: 'e.g., Moon Landing'),
              ),
              const SizedBox(height: 16),
              TextField(
                controller: descController,
                decoration: const InputDecoration(labelText: 'Brief Description'),
                maxLines: 3,
              ),
              const SizedBox(height: 16),
              TextField(
                controller: dateController,
                decoration: const InputDecoration(labelText: 'Event Date (YYYY-MM-DD)'),
              ),
            ],
          ),
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
          ElevatedButton(
            style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFFBC6FF1), foregroundColor: Colors.white),
            onPressed: () async {
              if (titleController.text.isNotEmpty) {
                try {
                  // Attempt insert
                  final data = {
                    'title': titleController.text,
                    'description': descController.text,
                    'incident_date': dateController.text,
                  };
                  
                  try {
                    await Supabase.instance.client.from('incidents').insert({
                      ...data,
                      'user_id': Supabase.instance.client.auth.currentSession?.user.id,
                    });
                  } catch (e) {
                    await Supabase.instance.client.from('incidents').insert(data);
                  }

                  if (mounted) {
                    Navigator.pop(context);
                    ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('History Archived successfully!')));
                  }
                } catch (e) {
                  if (mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Archive Error: ${e.toString()}')));
                  }
                }
              }
            },
            child: const Text('ARCHIVE'),
          ),
        ],
      ),
    );
  }

  void _showDeepDive(BuildContext context, String title, String? description) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) => DraggableScrollableSheet(
        initialChildSize: 0.85,
        maxChildSize: 0.95,
        minChildSize: 0.6,
        builder: (_, controller) => Container(
          decoration: const BoxDecoration(
            color: AppTheme.surface,
            borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
          ),
          child: StatefulBuilder(
            builder: (context, setModalState) {
              return FutureBuilder<Map<String, String>>(
                future: _currentReport != null ? Future.value(_currentReport) : ArchiveAIService.getDeepDive(title, description).then((value) {
                  _currentReport = value;
                  return value;
                }),
                builder: (context, snapshot) {
                  return ListView(
                    controller: controller,
                    padding: const EdgeInsets.all(24),
                    children: [
                      Center(
                        child: Container(
                          width: 40,
                          height: 4,
                          decoration: BoxDecoration(color: Colors.blueGrey, borderRadius: BorderRadius.circular(2)),
                        ),
                      ),
                      const SizedBox(height: 24),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Row(
                            children: [
                              Container(
                                padding: const EdgeInsets.all(8),
                                decoration: BoxDecoration(color: AppTheme.primary.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(8)),
                                child: const Icon(Icons.auto_awesome, color: AppTheme.primary),
                              ),
                              const SizedBox(width: 12),
                              Text('AI DEEP DIVE', style: GoogleFonts.outfit(fontWeight: FontWeight.bold, letterSpacing: 1, color: AppTheme.primary)),
                            ],
                          ),
                          if (snapshot.hasData)
                             getRowButtons(snapshot.data!, title),
                        ],
                      ),
                      const SizedBox(height: 24),
                      if (snapshot.connectionState == ConnectionState.waiting)
                         const Center(child: CircularProgressIndicator(color: AppTheme.primary))
                      else if (snapshot.hasError)
                         Text("Analysis Failed: ${snapshot.error}", style: const TextStyle(color: Colors.redAccent))
                      else ...[
                        Text(
                          snapshot.data?['title'] ?? title,
                          style: GoogleFonts.outfit(fontSize: 24, fontWeight: FontWeight.bold, color: Colors.white),
                        ),
                        const SizedBox(height: 16),
                        Container(
                          padding: const EdgeInsets.all(16),
                          decoration: BoxDecoration(
                             color: AppTheme.slate,
                             borderRadius: BorderRadius.circular(12),
                          ),
                          child: Text(
                             snapshot.data?['intro'] ?? '',
                             style: GoogleFonts.outfit(fontSize: 16, height: 1.5, color: Colors.blueGrey[100]),
                          ),
                        ),
                        const SizedBox(height: 24),
                        AspectRatio(
                           aspectRatio: 16/9,
                           child: ClipRRect(
                             borderRadius: BorderRadius.circular(12),
                             child: Stack(
                               fit: StackFit.expand,
                               children: [
                                 Image.network(
                                    snapshot.data?['image_url'] ?? 'https://loremflickr.com/800/400/history,${Uri.encodeComponent(title)}',
                                    fit: BoxFit.cover,
                                    errorBuilder: (c, e, s) => Container(color: Colors.grey[900], child: const Icon(Icons.broken_image)),
                                 ),
                                 // Watermark
                                 Center(
                                   child: Transform.rotate(
                                     angle: -0.2,
                                     child: Text(
                                       'Keyan ARTS',
                                       style: GoogleFonts.outfit(
                                         color: Colors.white.withValues(alpha: 0.15),
                                         fontSize: 48,
                                         fontWeight: FontWeight.bold,
                                       ),
                                     ),
                                   ),
                                 ),
                               ],
                             ),
                           ),
                        ),
                        const SizedBox(height: 24),
                        // Markdown Rendereing
                        MarkdownBody(
                          data: snapshot.data?['content'] ?? '',
                          styleSheet: MarkdownStyleSheet(
                            p: GoogleFonts.outfit(fontSize: 15, height: 1.6, color: Colors.blueGrey[50]),
                            h1: GoogleFonts.outfit(fontSize: 20, fontWeight: FontWeight.bold, color: Colors.white),
                            h2: GoogleFonts.outfit(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.white),
                            h3: GoogleFonts.outfit(fontSize: 16, fontWeight: FontWeight.bold, color: AppTheme.primary),
                            listBullet: TextStyle(color: AppTheme.primary),
                          ),
                        ).animate().fadeIn(duration: 500.ms),
                      ]
                    ],
                  );
                },
              );
            }
          ),
        ),
      ),
    ).then((_) => _currentReport = null);
  }

  Widget getRowButtons(Map<String, String> data, String title) {
    return Row(
      children: [
        IconButton(
          icon: const Icon(Icons.picture_as_pdf, color: Colors.greenAccent),
          tooltip: 'Download Report',
          onPressed: () async {
            // Use Printing package to print the map content into a simple layout
            final pdf = pw.Document();
            pdf.addPage(pw.Page(
              build: (pw.Context context) => pw.Column(
                children: [
                   pw.Text(data['title'] ?? title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                   pw.SizedBox(height: 20),
                   pw.Text(data['intro'] ?? '', style: const pw.TextStyle(fontSize: 14)),
                   pw.SizedBox(height: 20),
                   pw.Text(data['content'] ?? '', style: const pw.TextStyle(fontSize: 12)),
                ]
              )
            ));
            await Printing.layoutPdf(onLayout: (format) async => pdf.save());
          },
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.background,
      appBar: AppBar(
        title: Text('KEYAN GROUPS VAULT', style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white)),
        backgroundColor: AppTheme.background,
        elevation: 0,
        actions: [
          IconButton(
            icon: const Icon(Icons.logout, color: Colors.blueGrey),
            onPressed: () async => await _client.auth.signOut(),
          ),
        ],
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(60),
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            child: TextField(
              controller: _searchController,
              onChanged: (val) => setState(() => _searchQuery = val.toLowerCase()),
              style: const TextStyle(color: Colors.white),
              decoration: InputDecoration(
                hintText: 'Search the archives...',
                hintStyle: const TextStyle(color: Colors.blueGrey),
                prefixIcon: const Icon(Icons.search, color: AppTheme.primary),
                filled: true,
                fillColor: AppTheme.surface,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
              ),
            ),
          ),
        ),
      ),
      drawer: Drawer(
        backgroundColor: AppTheme.surface,
        child: ListView(
          padding: EdgeInsets.zero,
          children: [
             DrawerHeader(
               decoration: const BoxDecoration(
                 color: AppTheme.background,
               ),
               child: Column(
                 crossAxisAlignment: CrossAxisAlignment.start,
                 mainAxisAlignment: MainAxisAlignment.end,
                 children: [
                   const Icon(Icons.shield_moon, size: 48, color: AppTheme.primary),
                   const SizedBox(height: 12),
                   Text('ARCHIVAL NODES', style: GoogleFonts.outfit(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold)),
                 ],
               ),
             ),
             ListTile(
               leading: const Icon(Icons.today, color: AppTheme.primary),
               title: const Text('Today in History', style: TextStyle(color: Colors.white)),
               onTap: () {
                 Navigator.pop(context);
                 Navigator.push(context, MaterialPageRoute(builder: (context) => const CurrentAffairsPage()));
               },
             ),
             ListTile(
               leading: const Icon(Icons.picture_as_pdf, color: AppTheme.primary),
               title: const Text('Image to PDF Protocol', style: TextStyle(color: Colors.white)),
               onTap: () {
                 Navigator.pop(context);
                 _pickAndConvertImages();
               },
             ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _addIncident,
        backgroundColor: AppTheme.primary,
        child: const Icon(Icons.add, color: Colors.white),
      ),
      body: StreamBuilder<List<Map<String, dynamic>>>(
        stream: _stream,
        builder: (context, snapshot) {
          if (snapshot.hasError) return Center(child: Text("Error: ${snapshot.error}", style: const TextStyle(color: Colors.red)));
          if (!snapshot.hasData) return const Center(child: CircularProgressIndicator(color: AppTheme.primary));

          var list = snapshot.data!;
          
          if (_searchQuery.isNotEmpty) {
            list = list.where((item) {
              final title = (item['title'] ?? '').toString().toLowerCase();
              final desc = (item['description'] ?? '').toString().toLowerCase();
              return title.contains(_searchQuery) || desc.contains(_searchQuery);
            }).toList();
          }

          if (list.isEmpty) {
            if (_searchQuery.isNotEmpty) {
              return Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Icon(Icons.travel_explore, size: 64, color: Colors.blueGrey),
                    const SizedBox(height: 24),
                    Text(
                      "No records for \"${_searchQuery.toUpperCase()}\"",
                      style: const TextStyle(color: Colors.white70),
                    ),
                    const SizedBox(height: 32),
                    ElevatedButton.icon(
                      onPressed: () => _reconstructHistory(_searchQuery),
                      icon: const Icon(Icons.auto_awesome),
                      label: const Text("LAUNCH AI DISCOVERY"),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppTheme.primary,
                        foregroundColor: Colors.white,
                      ),
                    ),
                  ],
                ),
              );
            }
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.folder_open, size: 64, color: Colors.blueGrey),
                  const SizedBox(height: 16),
                  const Text("Archive is empty.", style: TextStyle(color: Colors.white70)),
                  const SizedBox(height: 16),
                  ElevatedButton(
                    onPressed: _addIncident,
                    child: const Text("ADD FIRST ENTRY"),
                  ),
                ],
              ),
            );
          }

          return ListView.builder(
            padding: const EdgeInsets.all(16),
            itemCount: list.length,
            itemBuilder: (context, index) {
              final incident = list[index];
              return Padding(
                padding: const EdgeInsets.only(bottom: 12),
                child: InkWell(
                  onTap: () => _showDeepDive(context, incident['title'], incident['description']),
                  borderRadius: BorderRadius.circular(12),
                  child: Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: AppTheme.surface,
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: Colors.white.withValues(alpha: 0.05)),
                    ),
                    child: Row(
                      children: [
                        if (incident['image_url'] != null && incident['image_url'].toString().isNotEmpty)
                          ClipRRect(
                             borderRadius: BorderRadius.circular(8),
                             child: Image.network(
                               incident['image_url'],
                               width: 60,
                               height: 60,
                               fit: BoxFit.cover,
                               errorBuilder: (c,e,s) => Container(width: 60, height:60, color: AppTheme.slate),
                             ),
                          )
                        else
                          Container(
                            width: 60,
                            height: 60,
                            decoration: BoxDecoration(color: AppTheme.slate, borderRadius: BorderRadius.circular(8)),
                            child: const Icon(Icons.history, color: Colors.blueGrey),
                          ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                incident['title'] ?? 'Untitled',
                                style: GoogleFonts.outfit(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.white),
                              ),
                              const SizedBox(height: 4),
                              Text(
                                incident['incident_date'] ?? '',
                                style: const TextStyle(color: Colors.blueGrey, fontSize: 12),
                              ),
                            ],
                          ),
                        ),
                        const Icon(Icons.chevron_right, color: Colors.blueGrey),
                      ],
                    ),
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }

  Future<void> _reconstructHistory(String query) async {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => Center(
        child: Container(
          padding: const EdgeInsets.all(32),
          decoration: BoxDecoration(
            color: AppTheme.slate,
            borderRadius: BorderRadius.circular(16),
            border: Border.all(color: AppTheme.primary),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const CircularProgressIndicator(color: AppTheme.primary),
              const SizedBox(height: 24),
              Text("RECONSTRUCTING HISTORY...", style: GoogleFonts.outfit(color: AppTheme.primary, fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              const Text("AI probes are analyzing archival patterns...", style: TextStyle(color: Colors.white70), textAlign: TextAlign.center),
            ],
          ),
        ).animate().scale(),
      ),
    );

    try {
      final discovery = await ArchiveAIService.discoverIncident(query);
      if (mounted) Navigator.of(context).pop(); // Close loading dialog

      if (discovery.isNotEmpty) {
        final Map<String, dynamic> insertData = {
          'title': discovery['title'],
          'description': discovery['description'],
          'incident_date': discovery['date'],
          'image_url': discovery['image_url'],
        };
        
        try {
           await Supabase.instance.client.from('incidents').insert(insertData);
        } catch (e) {
           // Retry without image if failure
           insertData.remove('image_url');
           await Supabase.instance.client.from('incidents').insert(insertData);
        }

              backgroundColor: AppTheme.primary,
              content: Text("NODE REGISTERED: ${discovery['title']}", style: const TextStyle(color: Colors.white)),
            ),
          );
          _searchController.clear();
          setState(() { _searchQuery = ""; });
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text("Discovery failed. No archival patterns found.")),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        if (Navigator.of(context).canPop()) Navigator.of(context).pop();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Discovery error: $e")),
        );
      }
    }
  }
}
