import { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { getDeepDive } from '../lib/api.js';
import { exportReportPdf } from '../lib/pdf.js';

const bannerFor = (incident) =>
  incident.image_url || `https://loremflickr.com/800/400/history,${encodeURIComponent(incident.title)}`;

export default function DeepDiveModal({ incident, onClose, onError }) {
  const [report, setReport] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    let live = true;
    getDeepDive(incident.title, incident.description)
      .then((r) => live && setReport(r))
      .catch((e) => {
        if (live) setError(e.message);
        onError?.(`Deep dive failed: ${e.message}`);
      });
    return () => {
      live = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [incident.id]);

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal deep-dive" onClick={(e) => e.stopPropagation()}>
        <div className="deep-dive-banner">
          <img src={bannerFor(incident)} alt="" onError={(e) => (e.currentTarget.style.opacity = '0.25')} />
          <button className="icon-btn" onClick={onClose} aria-label="Close">
            &times;
          </button>
        </div>

        <div className="deep-dive-head">
          <h2>{report?.title || incident.title}</h2>
        </div>

        <div className="deep-dive-scroll">
          {error ? (
            <p className="notice error">ACCESS ERROR: {error}</p>
          ) : !report ? (
            <div className="searching-note">
              <div className="spinner small" />
              RECONSTRUCTING ARCHIVAL DATA...
            </div>
          ) : (
            <>
              <p className="intro">{report.intro}</p>
              <div className="markdown">
                <ReactMarkdown>{report.content}</ReactMarkdown>
              </div>
            </>
          )}
        </div>

        <div className="modal-actions">
          <span className="search-hint">Generated by Keyan Groups AI Protocol</span>
          <button
            className="primary-btn"
            disabled={!report}
            onClick={() =>
              exportReportPdf({
                title: report.title,
                intro: report.intro,
                content: report.content,
              })
            }
          >
            EXPORT PDF REPORT
          </button>
        </div>
      </div>
    </div>
  );
}
