import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:image_picker/image_picker.dart';

class ImageToPdfService {
  static Future<void> generatePdfFromImages(List<XFile> images) async {
    final pdf = pw.Document();

    for (var image in images) {
      final imageBytes = await File(image.path).readAsBytes();
      final pdfImage = pw.MemoryImage(imageBytes);

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Stack(
              children: [
                pw.Center(
                  child: pw.Transform.rotate(
                    angle: -0.5,
                    child: pw.Opacity(
                      opacity: 0.1,
                      child: pw.Text('Keyan ARTS', style: pw.TextStyle(fontSize: 80, color: PdfColors.grey400, fontWeight: pw.FontWeight.bold)),
                    ),
                  ),
                ),
                pw.Center(
                  child: pw.Image(pdfImage, fit: pw.BoxFit.contain),
                ),
                pw.Align(
                  alignment: pw.Alignment.bottomCenter,
                  child: pw.Column(
                    mainAxisSize: pw.MainAxisSize.min,
                    children: [
                      pw.Divider(),
                      pw.Row(
                        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                        children: [
                          pw.Column(
                            crossAxisAlignment: pw.CrossAxisAlignment.start,
                            children: [
                              pw.Text('Generated by Keyan Groups AI Protocol', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
                              pw.UrlLink(
                                child: pw.Text("Developed by: Karthikeyan S", style: const pw.TextStyle(fontSize: 8, color: PdfColors.blue, decoration: pw.TextDecoration.underline)),
                                destination: "https://karthikeyans2006.github.io/",
                              ),
                              pw.UrlLink(
                                child: pw.Text("GitHub: KarthikeyanS2006", style: const pw.TextStyle(fontSize: 8, color: PdfColors.blue, decoration: pw.TextDecoration.underline)),
                                destination: "https://github.com/KarthikeyanS2006/",
                              ),
                            ],
                          ),
                          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            );
          },
        ),
      );
    }

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }
}
