import { jsPDF } from 'jspdf';

const AUTHOR_LINK = 'https://karthikeyans2006.github.io/';
const GITHUB_LINK = 'https://github.com/KarthikeyanS2006/';

function stripMarkdown(md) {
  return md
    .replace(/```[\s\S]*?```/g, (m) => m.replace(/```/g, ''))
    .replace(/!\[[^\]]*\]\([^)]*\)/g, '')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/\*\*|__|\*|_/g, '')
    .replace(/^\s*[-*+]\s+/gm, '  - ')
    .trim();
}

function addFrame(doc, label) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  // diagonal watermark
  doc.saveGraphicsState();
  doc.setTextColor(200);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(64);
  doc.text('Keyan ARTS', w / 2, h / 2, { align: 'center', angle: 28 });
  doc.restoreGraphicsState();
  // header
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(9);
  doc.text('KEYAN GROUPS ARCHIVAL REPORT', 18, 16);
  // footer
  doc.setDrawColor(200);
  doc.line(18, h - 20, w - 18, h - 20);
  doc.setFontSize(7);
  doc.setTextColor(100);
  doc.text('Generated by Keyan Groups AI Protocol', 18, h - 13);
  doc.text(`Developed by: Karthikeyan S  |  GitHub: KarthikeyanS2006`, 18, h - 9);
  doc.setTextColor(100);
  doc.text(label, w - 18, h - 13, { align: 'right' });
}

export function exportReportPdf({ title, intro, content }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  const margin = 18;
  const maxW = w - margin * 2;
  let y = 30;

  addFrame(doc, '');

  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  const titleLines = doc.splitTextToSize(title, maxW);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 8 + 4;
  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(0.8);
  doc.line(margin, y, margin + 60, y);
  y += 8;

  const body = `${intro}\n\n${stripMarkdown(content)}`;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  const lines = doc.splitTextToSize(body, maxW);
  for (const line of lines) {
    if (y > h - 30) {
      doc.addPage();
      addFrame(doc, `Page ${doc.internal.getCurrentPageInfo().pageNumber}`);
      y = 30;
    }
    doc.text(line, margin, y);
    y += 6;
  }

  const total = doc.internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    const pw = doc.internal.pageSize.getWidth();
    const ph = doc.internal.pageSize.getHeight();
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text(`Page ${i} of ${total}`, pw - 18, ph - 13, { align: 'right' });
    doc.text(`Developed by: Karthikeyan S`, 18, ph - 9);
    doc.text(`GitHub: KarthikeyanS2006`, 60, ph - 9);
    doc.text(AUTHOR_LINK, 100, ph - 9);
    doc.text(GITHUB_LINK, 145, ph - 9);
  }

  doc.save(`${title.replace(/[^\w\s-]/g, '').slice(0, 60) || 'archive-report'}.pdf`);
}

async function fileToJpegDataUrl(file) {
  const bitmap = await createImageBitmap(file);
  const maxW = 1400;
  const scale = Math.min(1, maxW / bitmap.width);
  const canvas = document.createElement('canvas');
  canvas.width = Math.round(bitmap.width * scale);
  canvas.height = Math.round(bitmap.height * scale);
  canvas.getContext('2d').drawImage(bitmap, 0, 0, canvas.width, canvas.height);
  return { dataUrl: canvas.toDataURL('image/jpeg', 0.92), w: canvas.width, h: canvas.height };
}

export async function exportImagesPdf(files) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();

  let first = true;
  for (const file of files) {
    const { dataUrl, w: iw, h: ih } = await fileToJpegDataUrl(file);
    if (!first) doc.addPage();
    first = false;

    addFrame(doc, '');
    const pad = 18;
    const maxW = w - pad * 2;
    const maxH = h - pad * 2 - 10;
    const scale = Math.min(maxW / iw, maxH / ih);
    const dw = iw * scale;
    const dh = ih * scale;
    doc.addImage(dataUrl, 'JPEG', (w - dw) / 2, pad + (maxH - dh) / 2, dw, dh);

    const total = doc.internal.getNumberOfPages();
    const cur = doc.internal.getCurrentPageInfo().pageNumber;
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text(`Page ${cur} of ${total}`, w - 18, h - 13, { align: 'right' });
  }

  doc.save('keyan-archive-scan.pdf');
}
